### ISSUE TITLE
pip search

### ISSUE THREAD

**Issue by pradyunsg** [shubhodeep9/pipsearch#1]
Hey!

What does this library do differently from actually running `pip search`?

**Comment by shubhodeep9** [comment]
Well as you know, `pip search` is a bash tool, but this is just small python library, that could be used for any program.
Usage: 
`import pipsearch`
`print (pipsearch.search('package-term'))`
Future scope: to integrate it with separate application, that generates setup files.

**Comment by pradyunsg** [comment]
I meant, is the information provided different? If so - how?

> this is just small python library, that could be used for any program.

Or you can get the output of running `pip search` and parse it. (:

> Future scope: to integrate it with separate application, that generates setup files.

Interesting... :P

**Comment by shubhodeep9** [comment]
It parses through pypa search results. That gives output according to the weight of the searched term.

Upon comparison, both results are different. Still I don't know on what basis does `pip search` provide results.

**Comment by pradyunsg** [comment]
FWIW, pip search uses the search method on PyPI's XML-RPC. More [here](https://warehouse.readthedocs.io/api-reference/xml-rpc/).

Maybe you can use that? Idk. Got a paper tomorrow. BBye.
