### ISSUE TITLE
Code requires linting

### ISSUE THREAD

**Issue by schedutron** [shubhodeep9/pipsearch#10]
For enhanced readability for new contributors, code should be listed and documented well.
@shubhodeep9 Please add the appropriate labels.

**Comment by schedutron** [comment]
@shubhodeep9 Please add the appropriate labels.

**Comment by shubhodeep9** [comment]
@schedutron You are absolutely right.
I knew this day would come :stuck_out_tongue_winking_eye: , was too lazy to do that.
Feel free to contribute.
