### ISSUE TITLE
Make CLI for convenient searches

### ISSUE THREAD

**Issue by schedutron** [shubhodeep9/pipsearch#14]
The API should take inputs like `pipsearch pygame` and output the results in an easily readable format.

**Comment by schedutron** [comment]
@shubhodeep9 Please add appropriate labels.

**Comment by biggydbs** [comment]
I am willing to solve this issue, assign it to me.

**Comment by shubhodeep9** [comment]
@biggydbs Hi, 
I can only assign to people who have already contributed to this repo. [GitHub bug or feature]
So why don't you proceed with the work, create PR, and we will see to merge.

**Comment by biggydbs** [comment]
Okay, And how do you define easily readable format ? Like pretty printing sort of ?
