### ISSUE TITLE
Make setup.py

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/pipsearch#2]
Make installer script for the library, and with requirements.

**Comment by Ilozuluchris** [comment]
@shubhodeep9  Just to be sure,you want
`from__future__ import absolute_import, division, print_function
from bs4 import BeautifulSoup
import requests
import re`

to be installed by the setup.py file

**Comment by shubhodeep9** [comment]
@Ilozuluchris yes
So that the installation and execution becomes easier for newer systems.

**Comment by Ilozuluchris** [comment]
@shubhodeep9  Okay let me have a crack at it

**Comment by shubhodeep9** [comment]
@Ilozuluchris Ok I will assign the issue to you.

**Comment by schedutron** [comment]
What about building a CLI for this, so that the user can just search like: `pipsearch pygame` and get all the nicely formatted results?

**Comment by shubhodeep9** [comment]
@schedutron Go ahead, create an issue and build it.
