### ISSUE TITLE
AttributeError Exception for no result

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/pipsearch#7]
This issue needs to be addressed, where if no result exists on PyPi, then it throws `AttributeError: 'NoneType' object has no attribute 'find_all'`.
UseCase example:
`import pipsearch
pipsearch.search('ooaisjdoiasjd')`
throws
`AttributeError: 'NoneType' object has no attribute 'find_all'`

**Comment by schedutron** [comment]
Let me do this.

**Comment by shubhodeep9** [comment]
@schedutron Cool, get on with it.
Don't forget to star the repo. 👍
